aikar/commands

- src/main/java/co/aikar/commands/ACF.java
https://github.com/aikar/commands/wiki/Using-ACF
According to the above wiki page that method should be static, but it's not. If I'm wrong, go ahead and close 💃
> Make ACF#createManager(...) static.

- src/main/java/co/aikar/commands/RegisteredCommand.java
Condense repeated logic for optional-typed resolvers.
Also adds support for multiple of these *optional* resolvers in one command. This means multiple Optional, Default, or SenderAware Resolvers without requiring arguments to be passed by the user on the back end of the command parameters.
> Allow multiple optional type resolvers on the tail-end of commands

- bungee/acf-bungee.iml
- bungee/pom.xml
- bungee/src/main/java/co/aikar/commands/ACFBungeeUtil.java
- bungee/src/main/java/co/aikar/commands/BungeeCommandCompletionContext.java
- bungee/src/main/java/co/aikar/commands/BungeeCommandCompletions.java
- bungee/src/main/java/co/aikar/commands/BungeeCommandContexts.java
- bungee/src/main/java/co/aikar/commands/BungeeCommandExecutionContext.java
- bungee/src/main/java/co/aikar/commands/BungeeCommandIssuer.java
- bungee/src/main/java/co/aikar/commands/BungeeCommandManager.java
- bungee/src/main/java/co/aikar/commands/BungeeRegisteredCommand.java
- bungee/src/main/java/co/aikar/commands/BungeeRootCommand.java
- bungee/src/main/java/co/aikar/commands/contexts/OnlineProxiedPlayer.java
- pom.xml
Add a module for a BungeeCord version of ACF.
> Add ACF-Bungee

- core/src/main/java/co/aikar/commands/BaseCommand.java
- core/src/main/java/co/aikar/commands/CommandManager.java
- core/src/main/java/co/aikar/commands/ExceptionHandler.java
- core/src/main/java/co/aikar/commands/RegisteredCommand.java
- example/src/main/java/co/aikar/acfexample/ACFExample.java
Add the ability to register exception handlers to handle exceptions that occur while executing a command
> Add custom Exception Handlers

- core/src/main/java/co/aikar/commands/RegisteredCommand.java
> Fix Optional parameters being resolved

- bungee/src/main/java/co/aikar/commands/BungeeCommandIssuer.java
When using TextComponent, the colors would reset on a new line, this fixes it
> Fix colors being reset on new line

- core/src/main/java/co/aikar/commands/CommandManager.java
- languages/core/acf-core_es.properties
- languages/minecraft/acf-minecraft_es.properties
Just saw that you could add translations so I added the spanish ones. Why a commit per edited file? Because I was lazy to open my IDE or use GitHub desktop (or Git itself) to do this so I did it on the web client.
> Adding spanish translations

- core/src/main/java/co/aikar/commands/CommandManager.java
- languages/core/acf-core_de.properties
- languages/minecraft/acf-minecraft_de.properties
This is a draft and up to discussion. Some other german speaker should definitely check those. I tried to find good translations while staying close to the original meaning. 
Should we really translate 'vanished' (I translated it into 'getarnt') or is it more sane it leave it in english since everybody will understand it easier when we use the proper term?
Also, I did not test them ingame or tried to load the file at all since I didn't had time yet to play with that. This is a good test for utf8 support I guess :D
> add german translations

- languages/core/acf-core_de.properties
- languages/core/acf-core_es.properties
- languages/core/acf-core_pl.properties
- languages/minecraft/acf-minecraft_de.properties
- languages/minecraft/acf-minecraft_en.properties
- languages/minecraft/acf-minecraft_es.properties
- languages/minecraft/acf-minecraft_pl.properties
> Translation fixes

- core/src/main/java/co/aikar/commands/CommandManager.java
- languages/core/acf-core_cs.properties
- languages/minecraft/acf-minecraft_cs.properties
I'm native czech speaker, translations were not tested in-game but should work.
> add czech translation

- languages/core/acf-core_en.properties
Sorry for the inconvenience of this typographical error.
> Fix typo of "inconvenience"

- languages/core/acf-core_en.properties
Sorry for any inconvenience which may have occurred due to this error.
> Fix typo of "occurred".

- core/src/main/java/co/aikar/commands/CommandCompletions.java
> WIP: Set default completion contexts

- sponge/src/main/java/co/aikar/commands/SpongeCommandManager.java
forgot to override the new abstract method in sponge
> Forgot to implement method for sponge

- bukkit/src/main/java/co/aikar/commands/ACFBukkitUtil.java
- core/src/main/java/co/aikar/commands/ACFUtil.java
- core/src/main/java/co/aikar/commands/BaseCommand.java
- sponge/src/main/java/co/aikar/commands/ACFSpongeUtil.java
Goes under #120
After this, only MultiMaps remain.
> Replace Guava Iterables

- core/src/main/java/co/aikar/commands/ACFPatterns.java
- core/src/main/java/co/aikar/commands/CommandManager.java
- core/src/main/java/co/aikar/commands/CommandReplacements.java
- core/src/main/java/co/aikar/commands/HelpEntry.java
- core/src/main/java/co/aikar/commands/Locales.java
- core/src/main/java/co/aikar/commands/RegisteredCommand.java
- core/src/main/java/co/aikar/commands/RootCommand.java
This seems kind of wrong to me. Somone calling RegisteredCommand#getHelpText out of context will run into the same issue.
> Fixes #165

- languages/core/acf-core_de.properties
- languages/minecraft/acf-minecraft_de.properties
- languages/minecraft/acf-minecraft_en.properties
I added missing German translations and improved some older ones.
> Complete German translation

- core/src/main/java/co/aikar/commands/CommandHelp.java
Fix for empty helps with CommandManager#generateCommandHelp()
> Set default help page to one. 

- core/src/main/java/co/aikar/commands/CommandManager.java
- languages/core/acf-core_bg.properties
- languages/minecraft/acf-minecraft_bg.properties
This commit adds bulgarian language to ACF
> Add bulgarian language

- bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
> Fix ConcurrentModificationException on server shutdown

- languages/minecraft/acf-minecraft_pt.properties
Also changed some sentences slightly to sound better in the Portuguese language.
> Translated vanish confirm section.

- languages/core/acf-core_cs.properties
- languages/minecraft/acf-minecraft_cs.properties
Fixed some strings, added missing ones, added missing Czech diacritics
> Update czech translation

- example/src/main/java/co/aikar/acfexample/ACFExample.java
Sorry, it just really bugged me.
> Fixed typo

- bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
- bukkit/src/main/java/co/aikar/commands/BukkitLocales.java
- bukkit/src/main/java/co/aikar/commands/MinecraftMessageKeys.java
- bungee/src/main/java/co/aikar/commands/BungeeCommandManager.java
- bungee/src/main/java/co/aikar/commands/BungeeLocales.java
- bungee/src/main/java/co/aikar/commands/MinecraftMessageKeys.java
- core/src/main/java/co/aikar/commands/ACFUtil.java
- core/src/main/java/co/aikar/commands/BaseCommand.java
- core/src/main/java/co/aikar/commands/CommandCompletionContext.java
- core/src/main/java/co/aikar/commands/CommandCompletions.java
- core/src/main/java/co/aikar/commands/CommandConditions.java
- core/src/main/java/co/aikar/commands/CommandManager.java
- core/src/main/java/co/aikar/commands/CommandReplacements.java
- core/src/main/java/co/aikar/commands/CommandRouter.java
- core/src/main/java/co/aikar/commands/MessageKeys.java
- core/src/main/java/co/aikar/commands/RegisteredCommand.java
- core/src/main/java/co/aikar/commands/apachecommonslang/ApacheCommonsLangUtil.java
- core/src/test/java/co/aikar/commands/TestCommandManager.java
- jda/src/main/java/co/aikar/commands/JDACommandManager.java
- jda/src/main/java/co/aikar/commands/JDACommandPermissionResolver.java
- languages/core/acf-core_tr.properties
- languages/minecraft/acf-minecraft_tr.properties
- sponge/src/main/java/co/aikar/commands/MinecraftMessageKeys.java
- sponge/src/main/java/co/aikar/commands/SpongeCommandManager.java
- sponge/src/main/java/co/aikar/commands/SpongeLocales.java
- velocity/src/main/java/co/aikar/commands/MinecraftMessageKeys.java
- velocity/src/main/java/co/aikar/commands/VelocityCommandManager.java
- velocity/src/main/java/co/aikar/commands/VelocityLocales.java
Adds Turkish language files and fix #255 issue.
> Turkish language Support and bug fix.

- languages/core/acf-core_pt.properties
- languages/minecraft/acf-minecraft_pt.properties
- Added missing Portuguese translations. 
- Tweaked the .properties file a little bit so every line matches its English counterpart.
- Fixed some grammar errors.
> Add missing Portuguese translations

- core/src/main/java/co/aikar/commands/ShowCommandHelp.java
Allows to throw the exception from outside the package.
> Made constructors public

- languages/core/acf-core_sv.properties
Fixed file encoding (from ISO-8859-1 to UTF-8) and also corrects translations, and adds missing ones.
> Fixes and updates acf-core_sv.properties

- core/src/main/java/co/aikar/commands/CommandManager.java
- languages/core/acf-core_ja.properties
- languages/minecraft/acf-minecraft_ja.properties
> Added Japaneses language

- languages/core/acf-core_bg.properties
- languages/core/acf-core_cs.properties
- languages/core/acf-core_de.properties
- languages/core/acf-core_en.properties
- languages/core/acf-core_es.properties
- languages/core/acf-core_hu.properties
- languages/core/acf-core_ja.properties
- languages/core/acf-core_nb.properties
- languages/core/acf-core_pl.properties
- languages/core/acf-core_pt.properties
- languages/core/acf-core_ru.properties
- languages/core/acf-core_sv.properties
- languages/core/acf-core_tr.properties
- languages/minecraft/acf-minecraft_bg.properties
- languages/minecraft/acf-minecraft_fr.properties
- languages/minecraft/acf-minecraft_hu.properties
- languages/minecraft/acf-minecraft_pl.properties
- languages/minecraft/acf-minecraft_sv.properties
Changed multiple language files from ansi to utf8 to solve encoding issues.
Added at some files the missing first line with an empty comment.
> Changed encoding to utf8

- languages/core/acf-core_ja.properties
- languages/minecraft/acf-minecraft_ja.properties
Missed this one last time. Shame on me
> Fix encodings for japanese language

- core/src/main/java/co/aikar/commands/CommandCompletionContext.java
- core/src/main/java/co/aikar/commands/RegisteredCommand.java
Attemp to fix a bug where commandCompletionContext.getResolvedArg returns null for IssuerOnly and IssuerAware inputs
> Fix CommandCompletionContext.getResolvedArg

- core/src/main/java/co/aikar/commands/CommandContexts.java
Relatively simple fix for issue #288 untested but shouldn't cause any additional issue.
Using the same error message from Integer context.
> Fix issue #288

- jda/pom.xml
- jda/src/main/java/co/aikar/commands/CommandConfig.java
- jda/src/main/java/co/aikar/commands/CommandConfigProvider.java
- jda/src/main/java/co/aikar/commands/JDACommandContexts.java
- jda/src/main/java/co/aikar/commands/JDACommandEvent.java
- jda/src/main/java/co/aikar/commands/JDACommandManager.java
- jda/src/main/java/co/aikar/commands/JDACommandPermissionResolver.java
- jda/src/main/java/co/aikar/commands/JDAListener.java
- jda/src/main/java/co/aikar/commands/JDAOptions.java
> Updated JDA support 4.2

- bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
Fix for https://github.com/aikar/commands/issues/293
> Fix NPE for plugins without special log prefix

- bukkit/src/main/java/co/aikar/commands/BukkitCommandContexts.java
Pretty straight forward:
- Catch IllegalArgumentException and use a ACF message (TODO: maybe a new MessageKey for that message?)
- only resolve valid player names
> Optimize OfflinePlayer context

- core/src/main/java/co/aikar/commands/CommandCompletions.java
Fixes #310 , which contains all the relevant info for this bug
> Autocomplete defaults when no completion is set

- brigadier/src/main/java/co.aikar.commands/ACFBrigadierManager.java
Fixes tab completion for the default method when brigadier api is enabled (#330)
> Fix @Default method brigadier tab completion

- languages/core/acf-core_ko.properties
- languages/minecraft/acf-minecraft_ko.properties
Added korean.
Accidentally removed previous pr
> Added korean

- core/src/main/java/co/aikar/commands/CommandManager.java
- languages/core/acf-core_it.properties
- languages/minecraft/acf-minecraft_it.properties
> Italian translation

- bukkit/src/main/java/co/aikar/commands/BukkitCommandIssuer.java
- bungee/src/main/java/co/aikar/commands/BungeeCommandIssuer.java
- sponge/src/main/java/co/aikar/commands/SpongeCommandIssuer.java
- sponge10/src/main/java/co/aikar/commands/SpongeCommandIssuer.java
- velocity/src/main/java/co/aikar/commands/VelocityCommandIssuer.java
> Open CommandIssuer implementations for extension.

- bukkit/src/main/java/co/aikar/commands/ACFBukkitLocalesListener.java
This should be only 20%ish slower than normal method call, compared to the about 30x slower time of classic reflection, convenient for big servers or for when the event for whatever reason is called a lot
> Use MethodHandle API

- bukkit/src/main/java/co/aikar/commands/BukkitRootCommand.java
Similar idea to #415. This will allow customization to handling of command args and tab complete, such as support command args with space by parsing quotes.
> Open BukkitRootCommand implementations for extension
