aikar/commands

bungee/src/main/java/co/aikar/commands/BungeeCommandManager.java, bungee/src/main/java/co/aikar/commands/BungeeRootCommand.java
BungeeRootCommand did not have getDefCommand implemented, and thus Default commands were not being found and throwing NPE. This PR implements the method.
This PR also implements command unregistration through the Bungee API.
=> Bungee: Implement getDefCommand & command unregistration

bukkit/src/main/java/co/aikar/commands/ACFBukkitListener.java, bukkit/src/main/java/co/aikar/commands/BukkitCommandIssuer.java, bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java, bungee/src/main/java/co/aikar/commands/ACFBungeeListener.java, bungee/src/main/java/co/aikar/commands/BungeeCommandIssuer.java, bungee/src/main/java/co/aikar/commands/BungeeCommandManager.java, core/src/main/java/co/aikar/commands/CommandIssuer.java, core/src/main/java/co/aikar/commands/CommandManager.java, jda/src/main/java/co/aikar/commands/JDACommandEvent.java, sponge/src/main/java/co/aikar/commands/ACFSpongeListener.java, sponge/src/main/java/co/aikar/commands/SpongeCommandIssuer.java, sponge/src/main/java/co/aikar/commands/SpongeCommandManager.java
This adds the missing support for issuer locales in Sponge and BungeeCord.
I'm open for feedback. Here is a short summary.
* Added update task and delayed join listener in BungeeCord
* Similar to the implementation in Bukkit but without reflection
* Added settings change listener in Sponge
* No task needed. It fires an event every time the players changes the settings
* Moved setLocale method up to the CommandManager to remove the amount of duplicated code
* Sponge, Bukkit and BungeeCord would have a similar implementation only the UUID call is different. (See below)
* The Discord implementation doesn't uses it and will always use the fallback locale.
* Added Optional<UUID> getUniqueId to CommandIssuer. 
* Do you think `@Nullable` is better?
* Or should we add another generic in …
=> Add support for per issuer locale in Sponge and BungeeCord

core/src/main/java/co/aikar/commands/BaseCommand.java, core/src/main/java/co/aikar/commands/RegisteredCommand.java, jda/src/main/java/co/aikar/commands/JDACommandCompletions.java, jda/src/main/java/co/aikar/commands/JDACommandConfig.java, jda/src/main/java/co/aikar/commands/JDACommandContexts.java, jda/src/main/java/co/aikar/commands/JDACommandEvent.java, jda/src/main/java/co/aikar/commands/JDACommandExecutionContext.java, jda/src/main/java/co/aikar/commands/JDACommandManager.java, jda/src/main/java/co/aikar/commands/JDAOptions.java, jda/src/main/java/co/aikar/commands/JDARootCommand.java, jda/src/main/java/co/aikar/commands/annotation/Author.java, jda/src/main/java/co/aikar/commands/annotation/SelfUser.java
As Java 7 introduced [`MethodHandle`s](https://docs.oracle.com/javase/8/docs/api/java/lang/invoke/MethodHandle.html), ACF should also use them to invoke as it is faster than reflection. It finds all the data it needs upon creating it, while reflection does so when it's needed. This sure is a mix and match case for needs, but as all commands are registered to be used, it'd be smarter to use a little more processing upon registration than when it's required.
I've most likely missed something, but everything I found boiled down to the same class and the same method, so I'm assuming that's all it needs.
=> Use MethodHandles for invocation

core/src/main/java/co/aikar/commands/CommandManager.java, core/src/main/java/co/aikar/commands/Locales.java, languages/core/acf-core_nb.properties, languages/core/acf-core_nn.properties, languages/minecraft/acf-minecraft_nb.properties, languages/minecraft/acf-minecraft_nn.properties
Adds the two written languages of Norway: Bokmål & Nynorsk. The codes are nb and nn respectively, according to ISO 639-1: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
=> Add Norwegian bokmål & nynorsk

core/src/main/java/co/aikar/commands/RegisteredCommand.java
Fix exception thrown by incorrect function
As of #112 using Any command will throw an exception. This hotfix was supplied by @Proximyst 
This was edited and created on mobile don’t judge at the small description.
=> Fix methodHandle error

core/src/main/java/co/aikar/commands/BaseCommand.java, core/src/main/java/co/aikar/commands/CommandHelp.java, core/src/main/java/co/aikar/commands/RegisteredCommand.java, core/src/main/java/co/aikar/commands/annotation/Private.java, example/src/main/java/co/aikar/acfexample/ACFExample.java
implements #123
seems to work fine
=> add a new annotation to hide commands from tabcompletion and help

jda/src/main/java/co/aikar/commands/JDACommandManager.java, jda/src/main/java/co/aikar/commands/JDAMessageFormatter.java
Because Discord does not support coloring messages outside of embeddable fields, it is safe to use a simple message formatter than just returns the message itself.
As I was testing my previous PR, I noticed messages coming through with coloring symbols (e.g. `<c1></c1>`), and each only went up to `c3` maximum. Finally, I figured out these were colors that needed to be handled in each case.
To remove colored messages from Discord, the message formatter is passed three empty strings for each of `c1`, `c2`, and `c3` respectively.
Finally, the default formatter is set inside of `JDACommandManager` but can always be overridden by the user.
=> Reimplement JDAMessageFormatter for Discord

jda/src/main/java/co/aikar/commands/CommandPermissionResolver.java, jda/src/main/java/co/aikar/commands/JDACommandEvent.java, jda/src/main/java/co/aikar/commands/JDACommandManager.java, jda/src/main/java/co/aikar/commands/JDACommandPermissionResolver.java, jda/src/main/java/co/aikar/commands/JDAOptions.java
This pull request is an initial attempt at implementing permission for commands for the JDA module.
It includes one added file, **JDACommandPermissionResolver** which implements CommandPermissionResolver.
I created a map to store the Discord permission offsets stored mapped by their kebab-cased name (i.e. "ADMINISTRATOR" becomes "administrator", "MANAGE_SERVER" becomes "manage-server".
The implementation of `hasPermission(JDACommandEvent, String)` is fairly simple:
- Get the issuer's Member object
- Check if it's null; if so, return false.
- Get the permission offset from the aforementioned map
- Check if it's null; if so, return false.
- Return whether or not the member has the permission.
---------------------------------------
This PR allows new commands to use the `@CommandPermission` …
=> Implement CommandPermissionResolver

jda/src/main/java/co/aikar/commands/JDACommandContexts.java, jda/src/main/java/co/aikar/commands/annotation/Author.java, jda/src/main/java/co/aikar/commands/annotation/CrossGuild.java, jda/src/main/java/co/aikar/commands/annotation/SelfUser.java
In a previous PR, some contexts were not changed from **IssuerOnly** to **IssuerAware**. This has been patched.
I've added a context to resolve a Role. It makes use of the next item I added.
The CrossGuild annotation is used to signify whether or not the context is to be interpreted from a guild perspective or a bot perspective (i.e. all guilds). This annotation could probably be better named.
=> Repair context types, add Role context, add CrossGuild annotation

jda/src/main/java/co/aikar/commands/JDACommandContexts.java
When @ mentioning someone in Discord, if you manually click the user's name then the ID will be in the chat field as "<@!...>". However, one can _also_ mention a user like so "<@...>".
This PR handles both cases.
=> [JDA] Fix User context resolution

.gitignore, bukkit/src/main/java/co/aikar/commands/BukkitCommandExecutionContext.java, bukkit/src/main/java/co/aikar/commands/BukkitRootCommand.java, bungee/src/main/java/co/aikar/commands/BungeeCommandExecutionContext.java, core/src/main/java/co/aikar/commands/ACFUtil.java, core/src/main/java/co/aikar/commands/Annotations.java, core/src/main/java/co/aikar/commands/BaseCommand.java, core/src/main/java/co/aikar/commands/CommandCompletionContext.java, core/src/main/java/co/aikar/commands/CommandCompletions.java, core/src/main/java/co/aikar/commands/CommandConditions.java, core/src/main/java/co/aikar/commands/CommandContexts.java, core/src/main/java/co/aikar/commands/CommandExecutionContext.java, core/src/main/java/co/aikar/commands/CommandManager.java, core/src/main/java/co/aikar/commands/CommandParameter.java, core/src/main/java/co/aikar/commands/ConditionContext.java, core/src/main/java/co/aikar/commands/Locales.java, core/src/main/java/co/aikar/commands/RegisteredCommand.java, core/src/main/java/co/aikar/commands/RootCommand.java, core/src/main/java/co/aikar/commands/ShowCommandHelp.java, core/src/main/java/co/aikar/commands/apachecommonslang/ApacheCommonsExceptionUtil.java, example/src/main/java/co/aikar/acfexample/ACFExample.java, jda/src/main/java/co/aikar/commands/JDACommandCompletions.java, jda/src/main/java/co/aikar/commands/JDACommandManager.java, paper/src/main/java/co/aikar/commands/PaperAsyncTabCompleteHandler.java, sponge/src/main/java/co/aikar/commands/SpongeCommandExecutionContext.java, sponge/src/main/java/co/aikar/commands/SpongeCommandIssuer.java
@aikar 
Please check that I did it right.
Relates to #120, #127
=> Drop trivial Guava usages 

jda/src/main/java/co/aikar/commands/JDACommandPermissionResolver.java
=> Deny permissions if command is issued by a webhook

core/src/main/java/co/aikar/commands/CommandReplacements.java
The code is now checking for placeholders, that are not replaced. This would also warn the dev if he completely forgets to register a replacement. 
The downside of this is, that any %.* kind of pattern, that is NOT supposed to be a replacement will cause an error message. But since I couldn't come up for a reason to include % in any of the Annotation values other than a replacement, I decided this is much easier than checking all "old" commands when a replacement is registered.
Alternatively, I could collect all these unreplaced replacements and check against the collection when a new one is registered. This would not warn a dev that forgot to register the replacement, but on the other hand still allows the use of %. Please tell me what you think.
resolves #160
=> Improve logging concerning command replacements

core/src/main/java/co/aikar/commands/BaseCommand.java
This is so the SubCommands from the SubClasses get added to the SubCommand map before calling **addChild()**
=> Register SubClasses before Command register()

jda/src/main/java/co/aikar/commands/JDACommandManager.java
This PR is to allow users to unregister commands from the `JDACommandManager`
Currently slightly flawed, needs research. When re-registering it spits out a load of messages like so:
```
SEVERE: [ACF] ACF Error: settings registered subcommand boss role for root command settings - but it is already defined in settings
Sep 20, 2018 3:58:31 AM com.algorithmjunkie.freelance.gachapon.acf.JDACommandManager log
SEVERE: [ACF] 2 subcommands of the same prefix may not be spread over 2 different classes. Ignoring this.
```
Not sure if this is just for me, or if it's for all.
=> Add unregister method for JDA

bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
This resolves an issue where CraftBukkit has the locale field as private.
=> Switched getField to getDeclaredField for the locale field in BukkitCommandManager

core/src/main/java/co/aikar/commands/BaseCommand.java
Currently the BaseCommand#hasPermission method doesn't actually check if the user has all the required permissions to execute a command, resulting in the following issue:
If user has permission permission.a they can execute:
/example
/example test
/example sub
/example sub testsub
Which is proper but if the user doesn't have permission.a they can only execute:
/example sub testsub
Example code:
```java
@CommandAlias("example")
@CommandPermission("permission.a")
public class ExampleCommand extends BaseCommand {
@HelpCommand
public void help(CommandHelp help) {
help.showHelp();
}
@Subcommand("test")
public void test(CommandSender sender) {
sender.sendMessage("has permission to test?");
}
@Subcommand("sub")
public class ExampleBCommand extends BaseCommand {
@Subcommand("testsub")
public void …
```
=> BaseCommand#hasPermission checks the required permissions

pom.xml, velocity/pom.xml, velocity/src/main/java/co/aikar/commands/ACFVelocityListener.java, velocity/src/main/java/co/aikar/commands/ACFVelocityUtil.java, velocity/src/main/java/co/aikar/commands/MinecraftMessageKeys.java, velocity/src/main/java/co/aikar/commands/VelocityCommandCompletionContext.java, velocity/src/main/java/co/aikar/commands/VelocityCommandCompletions.java, velocity/src/main/java/co/aikar/commands/VelocityCommandContexts.java, velocity/src/main/java/co/aikar/commands/VelocityCommandExecutionContext.java, velocity/src/main/java/co/aikar/commands/VelocityCommandIssuer.java, velocity/src/main/java/co/aikar/commands/VelocityCommandManager.java, velocity/src/main/java/co/aikar/commands/VelocityConditionContext.java, velocity/src/main/java/co/aikar/commands/VelocityLocales.java, velocity/src/main/java/co/aikar/commands/VelocityMessageFormatter.java, velocity/src/main/java/co/aikar/commands/VelocityRootCommand.java, velocity/src/main/java/co/aikar/commands/contexts/OnlinePlayer.java
This PR adds support for the upcoming proxy Velocity.
https://www.velocitypowered.org/
A few note worthy issues:
- Velocity does not provide a static method for its ProxyServer instance, so the instance has to be passed in by the plugin with `new VelocityCommandManager(proxy, this)`
- Velocity does not provide a way to get the Plugin logger with the provided Plugin or PluginContainer, so it must be fetched using `Logger logger = LoggerFactory.getLogger(plugin.getClass());` UNTESTED
- Velocity uses an annotation to signify the main class, meaning it can't be passed around like the Bukkit and Bungeecord JavaPlugin and Plugin. An Object has to be passed in which the PluginContainer is extracted from it using the Proxy's PluginManager …
=> Added Velocity support

core/src/main/java/co/aikar/commands/RegisteredCommand.java
I want to use own annotations for help implementations (link, tooltips, short description etc.)
I can't access the method directly for the annotations, please add the getter ;)
=> Added Method-Getter in RegisteredCommand class

core/src/main/java/co/aikar/commands/InvalidCommandArgument.java
The title says everything. Oh, and the spaces, intellij pasted them when I did Ctrl + K to commit
=> Make InvalidCommandArgument a runtime exception

velocity/pom.xml, velocity/src/main/java/co/aikar/commands/ACFVelocityUtil.java, velocity/src/main/java/co/aikar/commands/VelocityMessageFormatter.java
Kyori text was the only thing needing updating.
I don't know why you're using tabs in the pom.xml, but I tried to keep it as best as possible. Intellij doesn't like them much.
=> Updated Velocity to latest

core/src/main/java/co/aikar/commands/RegisteredCommand.java
I created my own PaperCommandManager and want to share the completions, context resolver and conditions between multiple OwnCommandManagers. I have a static implementation which works fine except the command conditions.
Can we please change the command condition stuff here to use getters?
No breaking change and a nice thing for me.
=> Use getter for command conditions

languages/core/acf-core_fr.properties
I suspect e9857cb8 changed encoding for the file and messed up
diacritics.
Also fixed a slight typo on acf-core.help_no_results.
=> i18n,fr: fix garbled diacritics.

core/src/main/java/co/aikar/commands/CommandContexts.java
I found a little bug in the error messages in the command-stuff:
In the method call there is a context.popFirstArg() which removes the first argument from the arguments list. The error message uses the getFirstArg() (the first argument in the list, after the removal from the argument from popFirstArg()).
There is no need to change the method signature from parseAndValidateNumber, the alternative way is to simply getFirstArg() in front of the method call and use popFirstArg in the method.
=> Fix wrong output for default context resolver for numbers.

core/src/main/java/co/aikar/commands/Annotations.java, core/src/main/java/co/aikar/commands/annotation/CatchUnknown.java, core/src/main/java/co/aikar/commands/annotation/CommandAlias.java, core/src/main/java/co/aikar/commands/annotation/CommandCompletion.java, core/src/main/java/co/aikar/commands/annotation/CommandPermission.java, core/src/main/java/co/aikar/commands/annotation/Conditions.java, core/src/main/java/co/aikar/commands/annotation/Default.java, core/src/main/java/co/aikar/commands/annotation/Description.java, core/src/main/java/co/aikar/commands/annotation/Flags.java, core/src/main/java/co/aikar/commands/annotation/HelpCommand.java, core/src/main/java/co/aikar/commands/annotation/HelpSearchTags.java, core/src/main/java/co/aikar/commands/annotation/Optional.java, core/src/main/java/co/aikar/commands/annotation/PreCommand.java, core/src/main/java/co/aikar/commands/annotation/Private.java, core/src/main/java/co/aikar/commands/annotation/Single.java, core/src/main/java/co/aikar/commands/annotation/Split.java, core/src/main/java/co/aikar/commands/annotation/Subcommand.java, core/src/main/java/co/aikar/commands/annotation/Syntax.java, core/src/main/java/co/aikar/commands/annotation/Values.java, core/src/test/java/co/aikar/commands/AnnotationTest.java
This adds basic support for meta-annotations for commands and
parameters and allows users to create their own custom annotations
combining certain existing annotations and values. For example, a user
can now define their own `CustomAnnotation` which combines a
condition and a flag:
```java
@Conditions("conditionname:confitionconfig")
@Flags("flagconfig=flagvalue")
public @interface CustomAnnotation {}
```
(Necessary `@Retention` and `@Target` ignore for brevity)
And use it just like they would normally.
This works by recursively going through the annotations, instead of
just looking at the root level. The reason most existing annotations
had to be touched is for them to be allowed on other annotations as
most of them were restricted to method or fields.
Currently there's no limit on …
=> Support simple meta-annotations

bukkit/src/main/java/co/aikar/commands/BukkitRootCommand.java
Since plugins may use this interface to identify bukkit commands by their plugin, this helps identifying them better.
=> Implement PluginIdentifiableCommand in BukkitRootCommand

core/src/main/java/co/aikar/commands/RegisteredCommand.java
If a CompletionHandler returns a Collection with null there will be a NPE for @Values annotations.
This pr should fix it.
=> Bugfix @Values: Completion with null value will create a NPE

example/src/main/java/co/aikar/acfexample/SomeCommand.java
Not sure or its a real typo or it has been set to this on purpose.
=> Fixed the typo(?) from SomeCommand.Test.TestInner#onTest1

bungee/pom.xml, bungee/src/main/java/co/aikar/commands/BungeeRootCommand.java
https://github.com/SpigotMC/BungeeCord/commit/a47b8033857973588a0da98d3ebdc5d970176fa9
This commit added some magic stuff to BungeeCord to check permissions for commands.
ACF already overrides the getPermission method but hasPermission method is untouched.
I had to increase the BungeeCord-Api version to 1.13 but that should be no problem since BungeeCord is backwards compatible to 1.8.
=> Fix wrong BungeeCord command suggestions

core/src/main/java/co/aikar/commands/BaseCommand.java, core/src/main/java/co/aikar/commands/CommandHelp.java, core/src/main/java/co/aikar/commands/CommandHelpFormatter.java, core/src/main/java/co/aikar/commands/CommandParameter.java, core/src/main/java/co/aikar/commands/HelpEntry.java, core/src/main/java/co/aikar/commands/Locales.java, core/src/main/java/co/aikar/commands/RegisteredCommand.java, core/src/main/java/co/aikar/commands/annotation/Name.java
I added a name annotation to change the display name from a parameter.
Either you can use the name annotation directly:
```java
@Subcommand("test")
public class TestCmd extends BaseCommand {
@Default
public void onTest(Player executor,
@Name("Text")String word,
@Name("Anzahl")int amount) {
executor.sendMessage("Word: \"" + word + "\" and amount " + amount);
}
}
```
Or you can modify the name by adding the message key to the locale:
```java
manager.getLocales().addMessageStrings(manager.getLocales().getDefaultLocale(), 
Collections.singletonMap("acf.parameter.text", "Banane"));
```
With @Name annotation the names will be changed:
It should not affect backwards compatibility
I failed some git-branch things in https://github.com/aikar/commands/pull/263
Now I'm unable to reopen the old pull …
=> Add name annotation for parameters

bukkit/src/main/java/co/aikar/commands/BukkitLocales.java
- Messages can now be defined everywhere instead of second-level only
- The data types string, double, int, long and boolean are (still) supported
This pull request resolves #173. Other data types were supported before, but that is rarely useful I think, as having a `org.bukkit.Location` in your language file would result in an output like `Location{world=CraftWorld{name=world},x=-287.797836225297,y=70.5,z=-13.083220284478912,pitch=-29.70023,yaw=-90.7704}`.
If it's wanted to keep everything that isn't a ConfigurationSection, I'll go with it too and change that part.
Another improvement I could think of otherwise (or if  the string is null) would be to send a warn log message for invalid keys. What do you think about that?
=> Allow properly nesting of messages

CONTRIBUTORS.md, bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java, paper/src/main/java/co/aikar/commands/PaperAsyncTabCompleteHandler.java
I was just working on a plugin when I realized that the Async support enabled message didn't have the same prefix that was in my plugin.yml.
=> Fix Bukkit log prefix for custom prefixes

core/src/main/java/co/aikar/commands/RegisteredCommand.java
I already made a PR a while ago to handle CompletableFutures in the exception handler:
https://github.com/aikar/commands/commit/7583dc881019174e81074d3539765cb2b1083627
I realized that CompletableFuture implements CompletionStage. That PR is just a small optimization to be prepared for custom CompletionStages and is not breaking as every CompletableFuture is a CompletionStage.
=> exception check for CompletionStage instead of CompletableFuture

core/src/main/java/co/aikar/commands/RegisteredCommand.java
This exception is just a wrapper for the one thrown on invoked methods/constructors.
By unwrapping this we can go straight to the problem instead of scrolling down to find the real cause.
And sometimes server owners only send the first part of the Exception, leaving the cause behind.
Compare these stack traces:
Wrapped Exception: https://pastebin.com/raw/7tB7zDNn
Unwrapped Exception: https://pastebin.com/raw/7Vsy4SdL
=> Unwraps InvocationTargetException

core/src/main/java/co/aikar/commands/ACFPatterns.java, core/src/main/java/co/aikar/commands/CommandReplacements.java
- Adds a new pattern for CommandReplacements: ```%{<key>}```
- Maintains the old pattern ```%<key>```
- Disables warnings for when the old pattern is not replaced
=> Adds a new pattern for CommandReplacements: %{<key>}

languages/core/acf-core_de.properties
"um diesen Befehl auszuführen" is a final subordinate clause and therefore needs a comma (https://www.sprachschach.de/komma-vor-um/).
=> Fixed spelling mistake in German translation

jda/pom.xml
As of 11/26/2021, the final release of JDA 4.x has been marked as the official LTS for the 4.x series. (https://github.com/DV8FromTheWorld/JDA/releases/tag/v4.4.0). 
This PR compiles against the latest version. Minimal testing has been done without seeing many issues. Compilation works fine.
=> Update to the final release of JDA 4.x

pom.xml, velocity/pom.xml, velocity/src/main/java/co/aikar/commands/ACFVelocityUtil.java, velocity/src/main/java/co/aikar/commands/VelocityCommandCompletions.java, velocity/src/main/java/co/aikar/commands/VelocityCommandContexts.java, velocity/src/main/java/co/aikar/commands/VelocityCommandManager.java, velocity/src/main/java/co/aikar/commands/VelocityMessageFormatter.java, velocity/src/main/java/co/aikar/commands/VelocityRootCommand.java
Hi! I've added velocity 3.0.0 support with this PR. Here are two changes I made that may need to be looked into:
1. `NamedTextColor.NAMES.values().stream().map(namedTextColor -> namedTextColor)`
The `.map(namedTextColor -> namedTextColor)` was required, so intellij stopped complaining about not assignable types. I am not sure if that is intentional, but it seems to work.
2. 
```java
@Override
public CompletableFuture<List<String>> suggestAsync(Invocation invocation) {
return CompletableFuture.completedFuture(getTabCompletions(manager.getCommandIssuer(invocation.source()), getCommandName(), invocation.arguments()));
}
```
I am not sure if that needs to be implemented, but I did it either way. 
Let me know if I have to do any more changes to get this PR merged. Thanks!
=> Add velocity 3.0.0 support

velocity/pom.xml, velocity/src/main/java/co/aikar/commands/ACFVelocityUtil.java, velocity/src/main/java/co/aikar/commands/VelocityCommandCompletions.java, velocity/src/main/java/co/aikar/commands/VelocityCommandContexts.java, velocity/src/main/java/co/aikar/commands/VelocityCommandIssuer.java, velocity/src/main/java/co/aikar/commands/VelocityCommandManager.java, velocity/src/main/java/co/aikar/commands/VelocityMessageFormatter.java, velocity/src/main/java/co/aikar/commands/VelocityRootCommand.java
Ported Velocity to 3.1.0, I've tested it, and both command execution and completion seem to work as they should.
The main problem with this port was that old Velocity used pre 1.16 colors. However, the new Velocity didn't have any bindings for it. So, I've replaced it with NamedTextColor.
I've tried to make a few changes. I hope I didn't mess things up! Merry Christmas!
=> Port Velocity to 3.1.0

bukkit/src/main/java/co/aikar/commands/BukkitRootCommand.java
=> Fixes /help <plugin> messages not localized #296

core/src/main/java/co/aikar/commands/BaseCommand.java
ACF does only use one matching command to complete commands. Therefore overloaded commands doesn't get correctly completed.
This should fix this problem. There is no need to match a specific command here.
filterTabComplete(..) will remove all duplicated completions so there should be no duplicates in the completions.
=> Use every subcommand for command completions

bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java, bungee/src/main/java/co/aikar/commands/BungeeCommandManager.java
Add option to get plugin description file for queries in plugins
```java
@Dependency
private PluginDescriptionFile description;
description.getAuthor(); // get current author
```
I will update the wiki page after the PR has been accepted.
=> feat: add plugin description to dependency injection

.idea/compiler.xml, bukkit/src/main/java/co/aikar/commands/BukkitCommandContexts.java
A NullPointerException is thrown when attempting to add on to the parsed `x`, `y`, and `z` doubles as the `ACFUtil#parseDouble(String)` method fallbacks to null if unable to parse the provided string.
=> Fix NullPointerException when attempting to parse a location relative to the player's position with the `~` term

core/src/main/java/co/aikar/commands/CommandCompletions.java, core/src/main/java/co/aikar/commands/CommandManager.java
- feat: add deregister methods to completions and dependencies
- fix: change unregister to deregister
- feat: add javadocs to deregisterCompleition
- fix: add throws to javadocs for dependency methods
This might not be best practice but I would like this functionality.
=> Add deregister ability to completions and contexts

velocity/src/main/java/co/aikar/commands/VelocityRootCommand.java
seems like at the time Velocity got implemented here, someone forgot to check the permissions issuer had. 
closes #355
=> fix Velocity root command not checking for permissions correctly

bukkit/src/main/java/co/aikar/commands/ACFBukkitLocalesListener.java, bukkit/src/main/java/co/aikar/commands/ACFBukkitUtil.java, bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
Use PlayerLocaleChangeEvent for newer versions of minecraft instead of polling all players every few second to see if their locale has changed. This will be a slight performance improvement as player usually dont change locale that often and will very inefficient to keep polling. The polling method will still be kept as a fallback for older minecraft version where PlayerLocaleChangeEvent is not present.
=> Use PlayerLocaleChangeEvent instead of repeating task when available

core/src/main/java/co/aikar/commands/BaseCommand.java
I have my own subclass within an ACF command for my own use, but ACF will try to instantiate them as long as its only has 1 constructor parameter even if it doesn't related to adding a subcommand. So I added a isAssignableFrom check for the correct parameter type before ACF should try to instantiate.
```
[11:32:06 WARN]: java.lang.IllegalArgumentException: argument type mismatch
[11:32:06 WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:65)
[11:32:06 WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[11:32:06 WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[11:32:06 WARN]: 	at …
```
=> Fix instantiate subclass if constructor parameter is the command's type

core/src/main/java/co/aikar/commands/Annotations.java
This will allow use cases such as having a parent class with `@CommandAlias` so I do not have to add `@CommandAlias("mv")` to 20 different command classes.
```java
@CommandAlias("mv")
public abstract class CoreCommand extends MultiverseCommand {
// ...
}
class CloneCommand extends CoreCommand {
@Subcommand("clone")
void onCloneCommand(...) { }
}
```
And this will also me to create aliases to a command by extending the command class as such:
```java
class LegacyAlias extends CloneCommand {
@Override
@CommandAlias("mvclone")
void onCloneCommand(...) {
super.onCloneCommand(...);
}
}
```
=> Add support for getting annotation from parent class/method/parameter
